# Konfigurace buildu a nasazení pro Netlify
[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

# API proxy pro production STAG systém
[[redirects]]
  from = "/api/stag-production/*"
  to = "https://stag-ws.zcu.cz/:splat"
  status = 200
  force = true

  [redirects.headers]
    "X-Forwarded-Host" = "true"
    "Access-Control-Allow-Origin" = "*"
    "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"
    "Access-Control-Allow-Headers" = "Origin, X-Requested-With, Content-Type, Accept"

# API proxy pro demo STAG systém
[[redirects]]
  from = "/api/stag-demo/*"
  to = "https://stag-demo.zcu.cz/:splat"
  status = 200
  force = true

  [redirects.headers]
    "X-Forwarded-Host" = "true"
    "Access-Control-Allow-Origin" = "*"
    "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"
    "Access-Control-Allow-Headers" = "Origin, X-Requested-With, Content-Type, Accept"

# Cache SVG souborů pro lepší výkon
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache pro ostatní statické soubory
[[headers]]
  for = "/*.(js|css|woff|woff2|ttf|png|jpg|jpeg)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Přesměrování pro Single Page Application (musí být poslední)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
