# example netlify.toml
[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config

# API proxy pro production STAG systém
[[redirects]]
  from = "/api/stag-production/*"
  to = "https://stag-ws.zcu.cz/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "true"}

# API proxy pro demo STAG systém
[[redirects]]
  from = "/api/stag-demo/*"
  to = "https://stag-demo.zcu.cz/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "true"}

# Cache SVG souborů pro lepší výkon
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache pro ostatní statické soubory
[[headers]]
  for = "/*.(js|css|woff|woff2|ttf|png|jpg|jpeg)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
